{% set name = "kedro-neptune" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/neptune-ai/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 8550a5e8b185ae15794f7c4c3d3967384fed51edb57b553f6e412843736a4a75

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - neptune-client >=0.10.9
    - kedro >=0.17.0
    - ruamel.yaml ==0.17.10
    - click >=7.0.0
    - psutil >=5.8.0

test:
  imports:
    - kedro_neptune
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://neptune.ai/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Neptune Client integration with Kedro
  doc_url: https://docs.neptune.ai/integrations-and-supported-tools/
  dev_url: https://github.com/neptune-ai/kedro-neptune

extra:
  recipe-maintainers:
    - HubertJaworski
    - shnela
    - pitercl
    - pkasprzyk
    - Raalsky
